name: "Push images on release"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

on:
  push:
    tags:
      - v*
jobs:
  build-and-push-amd64-sriov-cni:
    runs-on: ubuntu-20.04
    name: Image push AMD64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_NAME }}
          tag-latest: false

      - name: Build and push sriov-cni
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}-amd64
            ${{ steps.docker_meta.outputs.tags }}:${{ github.sha }}
          file: ./Dockerfile

  build-and-push-arm64-sriov-cni:
    runs-on: ubuntu-20.04
    name: Image push ARM64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_NAME }}
          tag-latest: false

      - name: Build and push sriov-cni
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}-arm64
          file: ./Dockerfile.arm64

  build-and-push-ppc64le-sriov-cni:
    runs-on: ubuntu-20.04
    name: Image push ppc64le
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_NAME }}
          tag-latest: false

      - name: Build and push sriov-cni
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}-ppc64le
          file: ./Dockerfile.ppc64le

  push-manifest:
    runs-on: ubuntu-20.04
    needs: [build-and-push-amd64-sriov-cni,build-and-push-amr64-sriov-cni,build-and-push-ppc64le-sriov-cni]
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ env.IMAGE_NAME }}
        tag-latest: false

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create manifest for multi-arch images
      run: |
        # pull
        docker pull ${{ steps.docker_meta.outputs.tags }}-amd64
        docker pull ${{ steps.docker_meta.outputs.tags }}-arm64
        docker pull ${{ steps.docker_meta.outputs.tags }}-ppc64le
        # create
        docker manifest create ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-amd64 ${{ steps.docker_meta.outputs.tags }}-arm64 ${{ steps.docker_meta.outputs.tags }}-ppc64le
        # annotate
        docker manifest annotate ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-amd64 --arch amd64
        docker manifest annotate ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-arm64 --arch arm64
        docker manifest annotate ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-ppc64le --arch ppc64le
        # push
        docker manifest push ${{ steps.docker_meta.outputs.tags }}
